"use client";
import "./globals.css";
import { Noto_Sans_Thai } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import AuthProvider from "./components/AuthProvider/AuthProvider";
import React, { useEffect, useState } from 'react'
import Sidebar from "./components/Sidebar/Sidebar";

const inter = Noto_Sans_Thai({ subsets: ["latin"] , weight: ["500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [nav, setNav] = useState(false);
  const [shownav , setShownav] = useState(false);

  useEffect(() => {
    if (window.location.href.includes("creator")) {
      setNav(true);
    }if (window.location.href.includes("contents/") || window.location.href.includes("viewer/") ){
      setShownav(true)
    }
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <AuthProvider>
            {shownav ? <></> : nav ? <Sidebar children={children} /> : <Navbar />}
            {nav ? <></> : children} {/* Removed extra curly braces */}
          </AuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
